training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  save_interval: 10
  checkpoint_dir: "checkpoints/"
  model_name: "speech_model"

model:
  input_dim: 256
  hidden_dim: 512
  output_dim: 80
  model_type: "transformer"
  language: "general"

audio:
  sample_rate: 22050
  mel_channels: 80
  hop_length: 256
  win_length: 1024
  n_fft: 1024
  min_level_db: -100
  ref_level_db: 20

data:
  train_data: "data/processed/train/"
  val_data: "data/processed/val/"
  test_data: "data/processed/test/"
  dataset_name: "speech_dataset"
  text_processing:
    normalize_numbers: true
    expand_abbreviations: true